# Config for single device LoRA finetuning in lora_finetune_single_device.py
# using a Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --hf-token <HF_TOKEN>
#
# To launch on a single device, run the following command from root:
#   tune run lora_dpo_single_device --config llama2/7B_lora_dpo_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run lora_dpo_single_device --config 7B_lora_dpo_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.

# Model Arguments
model:
  _component_: torchtune.models.llama3.lora_llama3_8b
  lora_attn_modules: ['q_proj', 'v_proj']
  lora_rank: 16
  lora_alpha: 32
  apply_lora_to_mlp: True
  apply_lora_to_output: True

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: checkpoints/Meta-Llama-3-8B-Instruct/original/tokenizer.model

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: checkpoints/Meta-Llama-3-8B-Instruct/original/
  checkpoint_files: [
    consolidated.00.pth
  ]
  recipe_checkpoint: null
  output_dir: outputs/Meta-Llama-3-8B-Instruct/dpo
  model_type: LLAMA3
resume_from_checkpoint: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.stack_exchanged_paired_dataset
  max_seq_len: 1024
seed: null
shuffle: True

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.05
  lr: 5e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.DPOLoss
  beta: 0.1
  label_smoothing: 0
  loss_type: sigmoid

# Training
epochs: 4
max_steps_per_epoch: null
gradient_accumulation_steps: 16
compile: False
eval_freq: 64
batch_size: 4

# Logging
output_dir: outputs/Meta-Llama-3-8B-Instruct/dpo_logs/
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: True
