# Config for single device LoRA finetuning in lora_finetune_single_device.py
# using a Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --hf-token <HF_TOKEN>
#
# To launch on a single device, run the following command from root:
#   tune run lora_dpo_single_device --config llama2/7B_lora_dpo_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run lora_dpo_single_device --config 7B_lora_dpo_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.

# Model Arguments
tokenizer:
  _component_: torchtune.models.mistral.mistral_tokenizer
  path: checkpoints/Mistral-7B-Instruct-v0.2/tokenizer.model


# Model Arguments
model:
  _component_: torchtune.models.mistral.lora_mistral_7b
  lora_attn_modules: ['q_proj', 'v_proj']
  lora_rank: 16
  lora_alpha: 32
  apply_lora_to_mlp: True
  apply_lora_to_output: True


checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: checkpoints/Mistral-7B-Instruct-v0.2
  checkpoint_files: [
    pytorch_model-00001-of-00003.bin,
    pytorch_model-00002-of-00003.bin,
    pytorch_model-00003-of-00003.bin
  ]
  recipe_checkpoint: null
  output_dir: checkpoints/Mistral-7B-Instruct-v0.2/lora
  model_type: MISTRAL
resume_from_checkpoint: False


# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.stack_exchanged_paired_dataset
  max_seq_len: 1024
seed: null
shuffle: True

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.05
  lr: 5e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.DPOLoss
  beta: 0.1
  label_smoothing: 0
  loss_type: sigmoid

# Training
epochs: 4
max_steps_per_epoch: null
gradient_accumulation_steps: 16
compile: False
eval_freq: 64
batch_size: 4

# Logging
output_dir: outputs/Mistral-7B-Instruct-v0.2/dpo_logs/
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: True
